name: CI

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install project and test deps
        run: |
          python -m pip install -U pip wheel
          pip install -e .[dev,test]
          pip install pytest pytest-cov

      - name: Run unit tests (skip IBM)
        run: |
          pytest -m "not ibm_token_required" --junitxml=reports/junit-local.xml --cov=qonscious --cov-report=xml --maxfail=1 -q

      - name: Run IBM-cloud tests (if token is present)
        if: ${{ secrets.IBM_QUANTUM_TOKEN != '' }}
        env:
          IBM_QUANTUM_TOKEN: ${{ secrets.IBM_QUANTUM_TOKEN }}
        run: |
          pytest -m "ibm_token_required" --junitxml=reports/junit-ibm.xml --maxfail=1 -q

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-reports
          path: reports/*.xml

      - name: Upload coverage to Codecov (optional)
        if: always()
        uses: codecov/codecov-action@v5
        with:
          files: coverage.xml
          # token is only needed for private repos or some setups:
          # token: ${{ secrets.CODECOV_TOKEN }}