name: CI

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    env:
          IBM_QUANTUM_TOKEN: ${{ secrets.IBM_QUANTUM_TOKEN }}
          IONQ_API_KEY: ${{ secrets.IONQ_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install project and test deps
        run: |
          python -m pip install -U pip wheel
          pip install -e .[dev,test]
          pip install pytest pytest-cov

      - name: Run unit tests (skip IBM and IONQ)
        run: |
          pytest -m "not (ibm_token_required or ionq_apikey_required)" -q

      - name: Run IBM-cloud tests (if token is present)
        if: env.IBM_QUANTUM_TOKEN != ''
        run: |
          pytest -m "ibm_token_required" -q

      - name: Run IONQ-cloud tests (if token is present)
        if: env.IONQ_API_KEY != ''
        run: |
          pytest -m "ionq_apikey_required" -q

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-reports
          path: reports/*.xml
